spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qianchengjava/spring-cloud-master
#https://github.com/qianchengjava/spring-cloud-master
#https://github.com/baihezhuo/learngit

server:
  context-path: /
  port: 4000